export const restaurants = [
  {
    imageUrl:
      "https://media-cdn.tripadvisor.com/media/photo-s/18/84/f2/12/inside-pizza-hut-outlet.jpg",
    name: "Pizza Hut",
    rating: "4.6",
    city: "Mumbai",
    description: "Pizzas",
  },
  {
    imageUrl:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.architecturaldigest.in%2Fstory%2Fthis-mumbai-restaurant-by-chef-ritu-dalmia-is-a-spectacular-culinary-theatre%2F&psig=AOvVaw1k8pexWfdcmdhiKXNjYZkg&ust=1709579775184000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCJCu0Ivn2IQDFQAAAAAdAAAAABAE",
    name: "Dalmia's Fastfood",
    rating: "3.6",
    city: "Bhopal",
    description: "Snacks",
  },
  {
    imageUrl:
      "https://content3.jdmagicbox.com/comp/kanpur/p6/0512px512.x512.190621221047.i4p6/catalogue/burger-king-kanpur-burger-joints-47dry02xq5.jpg",
    name: "Burger King",
    rating: "4.2",
    city: "New Delhi",
    description: "Burgers",
  },
  {
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWHsLB2XFFNIdzQXWRR9FXP6I0bd5TDCiY0g&usqp=CAU",
    name: "Taco Bell",
    rating: "3.9",
    city: "Bangalore",
    description: "Mexican",
  },
  {
    imageUrl:
      "https://media.licdn.com/dms/image/D5622AQFPYgvOJeDbfg/feedshare-shrink_800/0/1688147582513?e=2147483647&v=beta&t=A2OBap5mCj1i4TJc9MmyC9nhwTQ1rlguzNRmsK3cNAA",
    name: "Subway",
    rating: "4.1",
    city: "Chennai",
    description: "Sandwiches",
  },
  {
    imageUrl:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fnicelocal.in%2Fhyderabad%2Frestaurants%2Fdominos_pizza-75e9%2F&psig=AOvVaw17Ebf44zBDYUD-w4U6ZKGp&ust=1709580140983000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCICR_bno2IQDFQAAAAAdAAAAABAE",
    name: "Domino's Pizza",
    rating: "4.4",
    city: "Hyderabad",
    description: "Pizza",
  },
  {
    imageUrl:
      "https://imgstaticcontent.lbb.in/lbbnew/wp-content/uploads/2017/10/27020935/city-center-kfc-1-%5E.jpg",
    name: "KFC",
    rating: "4.0",
    city: "Kolkata",
    description: "Fried Chicken",
  },
  {
    imageUrl: "",
    name: "McDonald's",
    rating: "4.3",
    city: "Pune",
    description: "Fast Food",
  },
  {
    imageUrl: "",
    name: "Starbucks",
    rating: "4.5",
    city: "Ahmedabad",
    description: "Coffee",
  },
  {
    imageUrl: "",
    name: "Wendy's",
    rating: "3.8",
    city: "Jaipur",
    description: "Fast Food",
  },
  {
    imageUrl: "",
    name: "Chipotle Mexican Grill",
    rating: "4.1",
    city: "Surat",
    description: "Mexican",
  },
  {
    imageUrl: "",
    name: "Panera Bread",
    rating: "4.0",
    city: "Lucknow",
    description: "Sandwiches",
  },
  {
    imageUrl: "",
    name: "Papa John's Pizza",
    rating: "4.2",
    city: "Nagpur",
    description: "Pizza",
  },
  {
    imageUrl: "",
    name: "Arby's",
    rating: "3.7",
    city: "Gurugram",
    description: "Sandwiches",
  },
  {
    imageUrl: "",
    name: "Five Guys",
    rating: "4.6",
    city: "Indore",
    description: "Burgers",
  },
  {
    imageUrl: "",
    name: "Dunkin' Donuts",
    rating: "3.9",
    city: "Visakhapatnam",
    description: "Donuts",
  },
  {
    imageUrl: "",
    name: "Panda Express",
    rating: "4.0",
    city: "Thane",
    description: "Chinese",
  },
  {
    imageUrl: "",
    name: "Tim Hortons",
    rating: "4.2",
    city: "Agra",
    description: "Coffee",
  },
  {
    imageUrl: "",
    name: "Cinnabon",
    rating: "4.1",
    city: "Varanasi",
    description: "Bakery",
  },
  {
    imageUrl: "",
    name: "A&W Restaurants",
    rating: "3.6",
    city: "Patna",
    description: "Fast Food",
  },
  {
    imageUrl: "",
    name: "Sbarro",
    rating: "3.7",
    city: "Ludhiana",
    description: "Pizza",
  },
];
